# Generated by Django 4.2.1 on 2023-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0004_address_created_at_address_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='arvmedication',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='cd4count',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='parish',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='physicalexam',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='prepstatusdetail',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='regimen',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='regimenlinecode',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.RenameField(
            model_name='viralload',
            old_name='facility_id',
            new_name='facility_temp',
        ),
        migrations.AddField(
            model_name='docket',
            name='facility_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlab',
            name='facility_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfacilityassignment',
            name='facility_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
