# Generated by Django 4.2.1 on 2023-06-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0006_remove_address_facility_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='address',
            new_name='address1',
        ),
    ]
