# Generated by Django 4.2.1 on 2023-06-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0008_address_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvmedication',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
        migrations.AddField(
            model_name='cd4count',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
        migrations.AddField(
            model_name='prepstatusdetail',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
        migrations.AddField(
            model_name='viralload',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
        migrations.AlterField(
            model_name='otherlab',
            name='facility',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='prep_app.facility'),
        ),
    ]
