# Generated by Django 4.2.1 on 2023-07-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0010_contraceptivemethodcode_financialsupportcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialhistory',
            name='imported',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='legacy_id',
        ),
    ]
