# Generated by Django 4.2.1 on 2023-07-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0012_sti_results_sti_testcodes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STI_Tests',
            new_name='STI_TestsDone',
        ),
    ]
