# Generated by Django 4.2.1 on 2023-07-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0013_rename_sti_tests_sti_testsdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='STI_Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('deactivated_at', models.BooleanField(default=False)),
            ],
        ),
    ]
