# Generated by Django 4.2.1 on 2023-07-05 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prep_app', '0015_remove_riskhistory_imported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason_not_starting_prep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('deactivated_at', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_date', models.DateField()),
                ('risk_keypop_profile', models.CharField(choices=[('MSM', 'MSM'), ('TRANS', 'TRANS'), ('HRM', 'HRM'), ('HRF', 'HRF'), ('Other', 'Other')], max_length=255, null=True)),
                ('sex_partner_hiv_positive', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True)),
                ('sex_partner_hiv_positive_not_on_art', models.BooleanField()),
                ('sex_partner_hiv_positive_on_art_6months', models.BooleanField()),
                ('sex_partner_hiv_positive_suspected_poor_adherence_to_art', models.BooleanField()),
                ('sex_partner_hiv_positive_detectable_hiv_viral_load', models.BooleanField()),
                ('sex_partner_hiv_positive_couple_trying_to_conceive', models.BooleanField()),
                ('sex_partner_high_risk_and_hiv_status_unknown', models.BooleanField()),
                ('has_sex_with_multiple_partners', models.BooleanField()),
                ('ongoing_ipv_gbv', models.BooleanField()),
                ('transactional_sex', models.BooleanField()),
                ('recent_sti_6months', models.BooleanField()),
                ('recurrent_use_pep', models.BooleanField()),
                ('recurrent_sex_under_influence_of_alcohol_drugs', models.BooleanField()),
                ('inconsistent_or_no_condom_use', models.BooleanField()),
                ('shared_needles_or_syringes', models.BooleanField()),
                ('blood_pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_kg', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)])),
                ('height_cm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(220), django.core.validators.MinValueValidator(20)])),
                ('liver_disease_treatment', models.CharField(max_length=255)),
                ('kidney_disease_treatment', models.CharField(max_length=255)),
                ('chronic_illness_other', models.CharField(max_length=255)),
                ('lmp_date', models.DateField(blank=True, null=True)),
                ('if_pregnant', models.CharField(choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], max_length=255)),
                ('plan_to_have_children', models.CharField(choices=[('Trying to conceive', 'Trying to conceive'), ('Future', 'Future'), ('No', 'No'), ('Dont know', "Don't know")], max_length=255)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('hepatitis_b_results', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not Done', 'Not Done')], max_length=50)),
                ('hepatitis_c_results', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not Done', 'Not Done')], max_length=50)),
                ('serum_creatinine', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not Done', 'Not Done')], max_length=50)),
                ('prep_initiation_additional_steps', models.TextField(blank=True, null=True)),
                ('prescribed_prep_at_initial_visit_date_of_initiation', models.DateField(blank=True, null=True)),
                ('adherence_counseling_done', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_adherence_counseling_done', to='prep_app.yesnocode')),
                ('breast_feeding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_breast_feeding', to='prep_app.yesnocode')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prep_app.client')),
                ('condoms_issued', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_condoms_issued', to='prep_app.yesnocode')),
                ('contraindications_for_TDF_FTC_TDF_3TC_TDF', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_contraindications_for_TDF_FTC_TDF_3TC_TDF', to='prep_app.yesnocode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prep_app.facility')),
                ('family_planning_female', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_family_planning_female', to='prep_app.yesnocode')),
                ('male_circumcised', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_male_circumcised', to='prep_app.yesnocode')),
                ('medically_ineligible_to_start_prep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_medically_ineligible_to_start_prep', to='prep_app.yesnocode')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('pregnant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_pregnant', to='prep_app.yesnocode')),
                ('prescribed_prep_at_initial_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_prescribed_prep_at_initial_visit', to='prep_app.yesnocode')),
                ('prescribed_prep_at_initial_visit_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prep_app.regimen')),
                ('prescribed_prep_at_initial_visit_regime_months_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prep_app.monthdurationcode')),
                ('previous_prep_use', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_previous_prep_use', to='prep_app.yesnocode')),
                ('reason_not_will_to_start_prep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prep_app.reason_not_starting_prep')),
                ('signs_of_acute_hiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_signs_of_acute_hiv', to='prep_app.yesnocode')),
                ('signs_of_sti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_signs_of_sti', to='prep_app.yesnocode')),
                ('willing_to_start_prep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment_willing_to_start_prep', to='prep_app.yesnocode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
