# Generated by Django 4.2.1 on 2023-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0016_reason_not_starting_prep_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='performed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
