# Generated by Django 4.2.1 on 2023-07-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0022_sexualhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sexualhistory',
            old_name='date',
            new_name='interview_date',
        ),
    ]
