# Generated by Django 4.2.1 on 2023-07-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0023_rename_date_sexualhistory_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexualhistory',
            name='last_sexual_encounter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sexualhistory',
            name='lmp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
