# Generated by Django 4.2.1 on 2023-07-26 21:57

from django.db import migrations, models
import prep_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0025_alter_sexualhistory_gender_last_sex_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[prep_app.models.validate_not_future_date]),
        ),
    ]
