# Generated by Django 4.2.1 on 2023-08-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0029_outofcarestatus_outofcarestatuscode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outofcarestatus',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prep_app.outofcarestatuscode'),
        ),
    ]
